version: 2.1

jobs:
  make-test-generate-report:
    docker:
      - image: cypress/base:14.16.0
    working_directory: cypress
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm install
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run tests:run
      - run:
          name: Generate rports
          command: npm run report:generate
      - store_artifacts:
          path: /cypress/reports/results/json/
          destination: html
      - store_test_results:
          path: /cypress/reports/results/json/mochawesome.json

workflows:
  assigment-mobiquirt-main:
    jobs:
      - make-test-generate-report